### ISSUE TITLE
只能获取到第一个订单

### ISSUE THREAD

**Issue by PlaneV** [imlonghao/python-alipay-tool#1]
作者好！我发现这个工具好不容易配置好环境，却只能获取到第一个订单，不会跳到第二个订单。
我的支付宝第一个订单是收入的，第二个订单是支出的，后面还有收入或者支出的订单。
不知道为什么没有办法抓取到第二个订单。作者能解决一下吗？先谢谢了！！

**Comment by imlonghao** [comment]
支出的订单不会被抓取，而是会被跳过

**Comment by PlaneV** [comment]
跳过第二个订单后，如果第三个订单是收入的，那么第三个订单会被抓取吗？

**Comment by imlonghao** [comment]
会的，目前只会抓取收入的订单。

**Comment by PlaneV** [comment]
奇怪的是，我这里只抓取到第一个订单，后面的都没有，结束程序重新试，还是只有第一个订单，我只在里面填了Key、cookie和api。

**Comment by imlonghao** [comment]
可能是验证有问题，我过几天试试吧。

**Comment by PlaneV** [comment]
谢谢您！
