### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by frankwei98** [imlonghao/python-alipay-tool#2]
Traceback (most recent call last):
File "alipay.py", line 75, in <module>
req = requests.get(url, cookies=cookies)
File "/usr/lib/python2.6/site-packages/requests/api.py", line 69, in get
return request('get', url, params=params, *_kwargs)
File "/usr/lib/python2.6/site-packages/requests/api.py", line 50, in request
response = session.request(method=method, url=url, *_kwargs)
File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 468, in request
resp = self.send(prep, *_send_kwargs)
File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 576, in send
r = adapter.send(request, *_kwargs)
File "/usr/lib/python2.6/site-packages/requests/adapters.py", line 423, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lab.alipay.com', port=443): Max retries exceeded with url: /consume/record/items.htm (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1b96a50>: Failed to establish a new connection: [Errno 110] Connection timed out',))

运行脚本后没几分钟就出现这样的情况

**Comment by imlonghao** [comment]
Connection timed out
应该是你服务器到支付宝超时导致的。

**Comment by PlaneV** [comment]
可能是环境问题，这个程序需要python2.7的，我忘了具体是哪个组件的需求了

**Comment by imlonghao** [comment]
如果是环境问题的话应该是不会提示连接超时的吧？

**Comment by PlaneV** [comment]
我配置没有成功的时候，运行程序也确实没有提示python版本的问题，而是提示其他问题，诸如ssl问题的提示我遇到最多。
python版本问题的提示是在安装某个组件的时候出现的，原谅我的记性不好，我真的忘记了是哪个组件了

**Comment by imlonghao** [comment]
@PlaneV 你的回答似乎与这个 issue 无关？
没有配置成功的话是不会成功运行这个程序的，版本问题我不知道你指的是什么，你可以另开一个 issue 而不是在别人的 issue 里回答。

**Comment by PlaneV** [comment]
我其实是提议他考虑一下有没有可能是python版本的问题。我不知道您是不是在python2.7以下版本成功运行过？

**Comment by imlonghao** [comment]
@PlaneV python 版本问题是绝对不会出现这样的错误的

**Comment by PlaneV** [comment]
好的，知道了

**Comment by frankwei98** [comment]
我试了好几个服务器了 都不行啊 东京、香港这些应该行啊 但是都出现了类似的问题
我觉得这个问题与Python版本无关 因为在运行了python 2.7.5的VPS里运行这个程序也会出现类似错误 我再看看 顺便问一下@imlonghao 你用的哪里的VPS运行？

**Comment by imlonghao** [comment]
@fa

**Comment by imlonghao** [comment]
@frankwei98 我到时候再试一试把，顺便提高一下容错，适当提高timeout时间把。
